### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "jinony99@gmail.com",
  "password": "1234"
}

### 인증 페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg3OTY2NTIxfQ.RfF8l4tqmH6iZkRJvskxMV6cOl5V8xWfAiyx2pHo1yo